#!/usr/bin/env python3
"""context-gc init — bootstrap the write barrier for a target repository.

This is step 0 of the GC lifecycle. It scans a repo for context-bearing files, clusters them into
candidate fact domains, and writes:

  - .context-gc/config.yml   scope globs, excludes, scanner toggles
  - SOURCES.md (skeleton)    one entry per candidate domain, status NOT_CHECKED

init never decides truth. It proposes a root map for a human to confirm. Roots it cannot infer are
left as UNKNOWN_ROOT so MARK and the user resolve them later.

Usage:
  python scripts/init_context_gc.py --target /path/to/repo
  python scripts/init_context_gc.py --target . --force
"""
from __future__ import annotations

import argparse
import collections
import json
import pathlib
import subprocess
import sys
import time

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from _common import (  # noqa: E402
    DEFAULT_EXCLUDES,
    iter_agent_context_files,
    iter_context_files,
    rough_token_count,
    skill_names,
)

CONFIG_NAME = "config.yml"


def _domain_for(rel: str) -> tuple[str, str]:
    """Map a file to a candidate (domain, role). Heuristic only; the user confirms later."""
    p = pathlib.PurePath(rel)
    parts = p.parts
    name = p.name
    if name in {"CLAUDE.md", "SOUL.md"} or ".claude" in parts:
        return "agent-context", "root" if name in {"CLAUDE.md", "SOUL.md"} else "copy"
    if "skills" in parts and name == "SKILL.md":
        return f"skill:{parts[parts.index('skills') + 1]}" if "skills" in parts and parts.index("skills") + 1 < len(parts) else "skills", "root"
    if name.lower().startswith("readme"):
        return "project-readme", "root"
    if name.lower().startswith("changelog"):
        return "changelog", "root"
    if p.suffix.lower() in {".yaml", ".yml"} and ("docker-compose" in name or "compose" in name):
        return "deployment-config", "root"
    if p.suffix.lower() in {".yaml", ".yml", ".json", ".toml", ".ini"}:
        return "config", "copy"
    if parts and parts[0] in {"docs", "documentation", "wiki"}:
        return "docs", "copy"
    return "misc-docs", "copy"


def build_domains(target: pathlib.Path, excludes: list[str]):
    domains: dict[str, list[tuple[str, str]]] = collections.defaultdict(list)
    for path in iter_context_files(target, excludes):
        rel = path.relative_to(target).as_posix()
        domain, role = _domain_for(rel)
        domains[domain].append((rel, role))
    return domains


def render_sources(domains, target_name: str) -> str:
    today = time.strftime("%Y-%m-%d")
    lines = [
        "# Drift authority map",
        "",
        f"Generated by `context-gc init` for `{target_name}`. This is the write barrier: each entry",
        "names a fact domain, its authoritative root, the copies that must match it, and how to re-check.",
        "",
        "Status starts at `NOT_CHECKED`. Confirm each root, then run MARK to move entries to",
        "`SYNCED` / `DRIFTED` / `FORK` / `HISTORICAL`.",
        "",
        "## Entries",
        "",
    ]
    for domain in sorted(domains):
        files = sorted(domains[domain])
        roots = [f for f, role in files if role == "root"] or [files[0][0]]
        copies = [f for f, role in files if f not in roots]
        root = roots[0]
        status = "NOT_CHECKED" if len(roots) == 1 else "UNKNOWN_ROOT"
        lines.append(f"### `{domain}` — candidate fact domain (confirm root)")
        lines.append("")
        lines.append(f"- **Root:** `{root}` (proposed; confirm or replace)")
        lines.append("- **Owner:** `unknown`")
        lines.append("- **Risk:** `medium`")
        if copies:
            lines.append("- **Copies:**")
            for c in copies[:12]:
                lines.append(f"  - `{c}` — must match root (confirm relationship)")
            if len(copies) > 12:
                lines.append(f"  - ... and {len(copies) - 12} more")
        else:
            lines.append("- **Copies:** (none detected)")
        lines.append("- **Re-check:** `python scripts/mark.py --target .`")
        lines.append(f"- **Last verified:** {today}")
        lines.append("- **Last checked by:** context-gc init")
        lines.append(f"- **Status:** `{status}`")
        lines.append("")
        lines.append("---")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_config(excludes: list[str], hands_off: bool = False) -> str:
    lines = [
        "# context-gc config (init-generated). Edit to refine scope.",
        "scope:",
        "  include:",
        '    - "**/*.md"',
        '    - "**/*.yml"',
        '    - "**/*.yaml"',
        '    - "**/*.json"',
        "  exclude:",
    ]
    for pat in excludes:
        lines.append(f'    - "{pat}"')
    lines += [
        "scanners:",
        "  link_check: false   # set true if lychee is installed",
        "  markdownlint: false",
        "  vale: false",
        "thresholds:",
        "  stale_days: 120     # doc older than its described code by N days is flagged",
        "  agent_context_tokens: 12000",
        "  max_memory_files: 20",
        "auto_mark:",
        "  enabled: true       # read-only watching is free and zero-risk; never SWEEP",
        "  threshold: 10",
        "  mode: quiet",
        "  max_seconds: 5",
        "minor_gc:",
        "  enabled: true       # detect + queue drift in the background; apply_safe gates any auto-edit",
        "  interval_dirty_cards: 10",
        "  interval_turns: 10",
        f"  apply_safe: {'true' if hands_off else 'false'}   # {'takeover/hands-off: auto-apply scalar+pointer fixes (memory/protected stay never-auto)' if hands_off else 'OFF until the user authorizes auto-fix once (setup asks); then scalar/pointer only'}",
        "  max_files_per_run: 3",
        "  max_seconds: 5",
        "  mode: conservative",
        "  require_clean_git: false",
        "  allow_fixers:",
        "    - \"scalar-sync\"",
        "    - \"pointer-copy\"",
        "    - \"generated-state-cleanup\"",
        "  protected:",
        "    - \"CLAUDE.md\"",
        "    - \"SOUL.md\"",
        "    - \"memory/**\"",
        "    - \"skills/**/SKILL.md\"",
        "    - \"docs/adr/**\"",
        "    - \"docs/sdd/**\"",
        "memory_gc:",
        "  enabled: false      # condense long/mid-term memory and profiles; never deletes evidence silently",
        "  mode: conservative",
        "  allow_archive: false # move superseded memory to Archive path only when true",
        "  max_files_per_run: 5",
        "  protected_subjects:",
        "    - \"identity\"",
        "    - \"credentials\"",
        "    - \"legal\"",
        "autonomy:",
        "  # Agent-first: a loop/agent self-resolves the drift it is ALLOWED to; the rest escalates to you.",
        "  # You own this boundary. level off|assist|auto|full. never_auto is a hard floor enforced in code:",
        "  # even full will not let an agent touch protected files, deletes, memory writes, or ambiguous items.",
        f"  level: {'auto' if hands_off else 'assist'}",
        "  agent_may_resolve:",
        "    - \"safe-mechanical\"   # scalar-sync ports, pointer-copy, generated-state",
        "  min_recommend_confidence: 0.0",
        "  never_auto:",
        "    - \"protected\"",
        "    - \"delete\"",
        "    - \"memory-condense\"",
        "    - \"unknown-root\"",
        "",
    ]
    return "\n".join(lines)


def render_profile(target: pathlib.Path, domains) -> tuple[str, dict]:
    context_files = list(iter_context_files(target, DEFAULT_EXCLUDES))
    agent_files = list(iter_agent_context_files(target, DEFAULT_EXCLUDES))
    skills = sorted(skill_names(target))
    memory_files = [p for p in agent_files if "memory" in pathlib.PurePath(p.relative_to(target).as_posix()).parts]
    skill_sizes = []
    for path in agent_files:
        rel = path.relative_to(target).as_posix()
        if "skills" in pathlib.PurePath(rel).parts and path.name == "SKILL.md":
            text = path.read_text(encoding="utf-8", errors="ignore")
            skill_sizes.append((rough_token_count(text), rel))
    skill_sizes.sort(reverse=True)
    agent_tokens = 0
    for path in agent_files:
        try:
            agent_tokens += rough_token_count(path.read_text(encoding="utf-8"))
        except Exception:
            pass
    ambiguous = [domain for domain, files in domains.items() if len([f for f, role in files if role == "root"]) != 1]
    recommended = "agent context" if agent_files else "docs/config roots"
    data = {
        "context_files": len(context_files),
        "agent_context_files": len(agent_files),
        "skill_count": len(skills),
        "memory_files": len(memory_files),
        "agent_context_tokens": agent_tokens,
        "ambiguous_domains": ambiguous,
        "largest_skills": skill_sizes[:5],
    }
    lines = [
        f"# context-gc profile — {target.name}",
        "",
        "This profile is a read-only heap sketch. It does not decide truth or sweep files.",
        "",
        f"- Context-bearing files: {len(context_files)}",
        f"- Agent-context files: {len(agent_files)}",
        f"- Skills: {len(skills)}",
        f"- Memory files: {len(memory_files)}",
        f"- Approx agent-context budget: ~{agent_tokens} tokens",
        f"- Ambiguous candidate domains: {len(ambiguous)}",
        "",
        "## Largest skills",
    ]
    if skill_sizes:
        for tokens, rel in skill_sizes[:5]:
            lines.append(f"- `{rel}` — ~{tokens} tokens")
    else:
        lines.append("- none detected")
    lines += [
        "",
        "## Recommended first MARK scope",
        "",
        f"Start with `{recommended}` and any files in `.context-gc/dirty.jsonl`; confirm roots before SWEEP.",
    ]
    return "\n".join(lines) + "\n", data


def build_setup_draft(domains) -> dict:
    """Machine-readable setup draft for the SKILL `setup` flow.

    Proposes a root per domain and flags ambiguity. It NEVER decides truth: ambiguous roots are
    listed for the SKILL to resolve with one AskUserQuestion each.
    """
    drafted = []
    for name in sorted(domains):
        files = sorted(domains[name])
        roots = [f for f, role in files if role == "root"]
        copies = [f for f, role in files if f not in roots]
        ambiguous = len(roots) != 1
        drafted.append({
            "domain": name,
            "proposed_root": (roots[0] if roots else (files[0][0] if files else "")),
            "candidate_roots": roots or [f for f, _ in files[:3]],
            "copies": copies[:12],
            "ambiguous": ambiguous,
            "suggested_status": "UNKNOWN_ROOT" if ambiguous else "NOT_CHECKED",
            "needs_question": ambiguous,
        })
    return {
        "domains": drafted,
        "ambiguous_count": sum(1 for d in drafted if d["ambiguous"]),
        "authorization_question": {
            "prompt": "Let me auto-fix mechanical low-risk drift (ports, pointers) in the background without asking each time?",
            "options": [
                {"label": "Yes — auto-fix safe mechanical items", "effect": {"minor_gc.apply_safe": True}},
                {"label": "No — queue everything for my review", "effect": {"minor_gc.apply_safe": False}},
            ],
            "note": "Sensitive agent/memory fixes always stay review-only regardless of this answer.",
        },
    }


def run_takeover_audit(target: pathlib.Path) -> dict:
    """First full GC — run MARK once and summarize the standing drift debt of an already-drifted repo.

    A project adopting context-gc when it is already drifted needs a baseline pass before incremental
    guarding makes sense: the detectors that do not require a confirmed SOURCES map (orphans,
    duplicates, stale docs, coverage gaps, agent/memory rot) surface the existing debt so it can be
    cleared in batches. Read-only — this is MARK; it never edits.
    """
    mark = pathlib.Path(__file__).resolve().parent / "mark.py"
    subprocess.run(
        [sys.executable, str(mark), "--target", str(target)],
        capture_output=True, text=True, encoding="utf-8", errors="replace",
    )
    fp = target / ".context-gc" / "findings.json"
    try:
        findings = json.loads(fp.read_text(encoding="utf-8")).get("findings", [])
    except Exception:
        findings = []
    by_sev = {"high": 0, "medium": 0, "low": 0}
    for f in findings:
        sev = f.get("severity", "low")
        by_sev[sev] = by_sev.get(sev, 0) + 1
    rank = {"high": 0, "medium": 1, "low": 2}
    top = sorted(findings, key=lambda f: rank.get(f.get("severity"), 3))[:8]
    return {"total": len(findings), "by_severity": by_sev, "top": top}


def main() -> int:
    ap = argparse.ArgumentParser(description="Bootstrap context-gc write barrier for a repo")
    ap.add_argument("--target", default=".", help="repository to initialize (default: cwd)")
    ap.add_argument("--force", action="store_true", help="overwrite existing SOURCES.md/config")
    ap.add_argument("--profile", action="store_true", help="write .context-gc/profile.md and profile.json")
    ap.add_argument("--guided", action="store_true", help="also write .context-gc/setup-draft.json for the SKILL setup flow")
    ap.add_argument("--takeover", action="store_true", help="hands-off adoption: write auto/apply-safe config, then run a first full audit of standing drift")
    a = ap.parse_args()

    target = pathlib.Path(a.target).resolve()
    if not target.is_dir():
        print(f"FAIL: target is not a directory: {target}")
        return 1

    state_dir = target / ".context-gc"
    state_dir.mkdir(exist_ok=True)
    config_path = state_dir / CONFIG_NAME
    sources_path = target / "SOURCES.md"

    if sources_path.exists() and not a.force:
        print(f"SOURCES.md already exists at {sources_path}. Use --force to regenerate (it will overwrite).")
        return 2

    domains = build_domains(target, DEFAULT_EXCLUDES)
    if not domains:
        print("No context-bearing files found. Nothing to initialize.")
        return 0

    sources_path.write_text(render_sources(domains, target.name), encoding="utf-8")
    if not config_path.exists() or a.force:
        config_path.write_text(render_config(DEFAULT_EXCLUDES, hands_off=a.takeover), encoding="utf-8")

    if a.profile or a.guided:
        profile_md, profile_data = render_profile(target, domains)
        (state_dir / "profile.md").write_text(profile_md, encoding="utf-8")
        (state_dir / "profile.json").write_text(json.dumps(profile_data, ensure_ascii=False, indent=2), encoding="utf-8")

    if a.guided:
        draft = build_setup_draft(domains)
        (state_dir / "setup-draft.json").write_text(json.dumps(draft, ensure_ascii=False, indent=2), encoding="utf-8")

    total = sum(len(v) for v in domains.values())
    print(f"OK: initialized context-gc for {target.name}")
    print(f"  domains: {len(domains)}  context files: {total}")
    print(f"  wrote: {sources_path.relative_to(target)}")
    print(f"  wrote: {config_path.relative_to(target)}")
    if a.profile or a.guided:
        print("  wrote: .context-gc/profile.md")
    if a.guided:
        print("  wrote: .context-gc/setup-draft.json")

    if a.takeover:
        audit = run_takeover_audit(target)
        bs = audit["by_severity"]
        print("")
        print(f"✓ context-gc has taken over {target.name} (hands-off: auto-mark + auto-fix safe mechanical drift)")
        print(f"  first full MECHANICAL audit — {audit['total']} standing item(s): "
              f"{bs.get('high', 0)} high, {bs.get('medium', 0)} medium, {bs.get('low', 0)} low")
        for f in audit["top"]:
            loc = f.get("file") or ", ".join(f.get("files", []))
            print(f"    {str(f.get('severity', '?')):6} {str(f.get('type', '?')):26} {loc}")
        if audit["total"] > len(audit["top"]):
            print(f"    … +{audit['total'] - len(audit['top'])} more in .context-gc/findings.json")
        print("  this counts only MECHANICALLY-visible debt (orphans, dupes, stale, rot). Value contradictions")
        print("  — \"which doc is right\" — are judgment-level and surface as you confirm each domain's root.")
        print("  from here: I auto-mark on edits and auto-apply safe scalar/pointer fixes; judgment items escalate to you.")
        nudge = "run the SKILL `review` flow" if a.guided else "clear the standing debt above in batches (highest severity first)"
        print(f"  next: {nudge} — each item needs your call on the root; the authority map fills in as you go.")
    elif a.guided:
        print("  next: run the SKILL `setup` flow to confirm ambiguous roots and finish managing drift.")
    else:
        print("  next: confirm roots in SOURCES.md, then run scripts/mark.py --target .")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
